'use client'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 FerrisWheel.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/FerrisWheel.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh geometry={nodes.Body3001.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body6001.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body16001.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body17001.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body18001.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body19.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body20.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body21001.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body22.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body23.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body24.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body25.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body4001.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body26.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body27.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body28.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body29.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body30.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body1.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body16.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body17.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body18.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body19001.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body8001.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body20001.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body21.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body22001.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body23001.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body24001.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body25001.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body1001.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body2.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body3.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body4.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body9.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body5.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body6.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body7.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body8.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body9001.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body10.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body11.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body10001.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body11001.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body12.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body14.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
      <mesh geometry={nodes.Body15.geometry} material={materials.F_3a28566953e0438bb9e279d09b111527_baked} scale={10} />
    </group>
  )
}

useGLTF.preload('/FerrisWheel.glb')
