'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/Connect4Robot.glb --transform 
Files: public/Connect4Robot.glb [1.68MB] > /Users/richard/Documents/richardbt.com/Connect4Robot-transformed.glb [113.97KB] (93%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Connect4Robot-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body1.geometry} material={materials.PaletteMaterial001} scale={0.394} />
      <mesh geometry={nodes.Body1006.geometry} material={materials.PaletteMaterial002} position={[-1.399, 5.894, -0.486]} rotation={[Math.PI / 2, -0.122, 0]} scale={0.394} />
      <mesh geometry={nodes.Body33.geometry} material={materials.PaletteMaterial003} position={[-1.399, 5.894, -0.486]} rotation={[Math.PI / 2, -0.122, 0]} scale={0.394} />
      <mesh geometry={nodes.Body1022.geometry} material={materials.PaletteMaterial004} position={[-1.633, 9.137, -1.877]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.394} />
    </group>
  )
}

useGLTF.preload('/Connect4Robot-transformed.glb')
