'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.17 public/Minecart.glb --transform 
Files: public/Minecart.glb [342.83KB] > /Users/richard/Documents/richardbt.com/Minecart-transformed.glb [35.82KB] (90%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Minecart-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={10}>
        <mesh geometry={nodes.Body1_1.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Body1_2.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Body1_3.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Body1_4.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Body1_5.geometry} material={materials.PaletteMaterial005} />
      </group>
    </group>
  )
}

useGLTF.preload('/Minecart-transformed.glb')
