'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.17 public/MountainWithCutouts.glb --transform 
Files: public/MountainWithCutouts.glb [1.68MB] > /Users/richard/Documents/richardbt.com/MountainWithCutouts-transformed.glb [83.83KB] (95%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/MountainWithCutouts-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={10}>
        <mesh geometry={nodes.MeshBody1__3___1__1.geometry} material={materials.F_0fcbb5ff8e1944608adf7f697efbb4c3} />
        <mesh geometry={nodes.MeshBody1__3___1__2.geometry} material={materials.F_07583f6ae86e4ec8a5450bf4aabdd6b1} />
      </group>
    </group>
  )
}

useGLTF.preload('/MountainWithCutouts-transformed.glb')
