'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.17 public/MountainTextured.glb --transform 
Files: public/MountainTextured.glb [2.19MB] > /Users/richard/Documents/richardbt.com/MountainTextured-transformed.glb [98.54KB] (95%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/MountainTextured-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.MeshBody1__3___1_.geometry} material={materials['F_ebc58cdcb27f4fcc9e9b420895a1f94a.002']} scale={0.394} />
    </group>
  )
}

useGLTF.preload('/MountainTextured-transformed.glb')
