'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.17 public/OreTile.glb --transform 
Files: public/OreTile.glb [3.19MB] > /Users/richard/Documents/richardbt.com/OreTile-transformed.glb [195.7KB] (94%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/OreTile-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body1.geometry} material={materials.PaletteMaterial001} position={[0, -2.838, -2.838]} rotation={[Math.PI / 2, 0, 0]} scale={10} />
      <group position={[12.361, -45.517, 15.214]} rotation={[0, 0.873, 0]} scale={10}>
        <mesh geometry={nodes.Body1002_1.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Body1002_2.geometry} material={materials.PaletteMaterial003} />
      </group>
      <mesh geometry={nodes.Body41.geometry} material={materials.PaletteMaterial004} position={[12.361, -45.517, 15.214]} rotation={[0, 0.873, 0]} scale={10} />
      <mesh geometry={nodes.Body1010.geometry} material={materials.PaletteMaterial005} position={[-56.833, -35.869, 2.955]} rotation={[-0.33, 1.49, 0.096]} scale={10} />
      <mesh geometry={nodes.MeshBody1__3___1_.geometry} material={materials.PaletteMaterial006} position={[0.178, 3, 2.919]} rotation={[0, -Math.PI / 3, 0]} scale={10} />
      <instancedMesh args={[nodes.Body3004.geometry, materials.PaletteMaterial002, 6]} instanceMatrix={nodes.Body3004.instanceMatrix} />
      <instancedMesh args={[nodes.Body1006.geometry, materials.PaletteMaterial002, 6]} instanceMatrix={nodes.Body1006.instanceMatrix} />
      <instancedMesh args={[nodes.Body1008.geometry, materials.PaletteMaterial004, 5]} instanceMatrix={nodes.Body1008.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/OreTile-transformed.glb')
