import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import SideBar from "@/components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="flex h-screen flex-col lg:flex-row p-4 lg:p-0 lg:overflow-hidden">
          <div className="lg:basis-1/3 lg:relative">
            <SideBar />
          </div>
          <div className="lg:basis-2/3 lg:overflow-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
